services:
  controller:
    build: ./controller
    container_name: controller
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./controller/observations/:/observations
      - ./controller/app/:/app:ro

  speech:
    build: ./speech
    container_name: speech
    ports:
      - "9559:9559"
      - "9700:9700" # sockets
      - "9701:9701" # http
    volumes:
      - ./speech/app/:/app:ro

  whisper:
    build: ./whisper
    container_name: whisper
    volumes:
      - ./whisper/app.py/:/app/app.py:ro

  pepper:
    build: ./pepper
    container_name: naoqi
    volumes:
      - ./pepper/app/:/app:ro

  # default voices: https://rhasspy.github.io/piper-samples
  tts:
    build: ./piper
    container_name: piper
    command: >
      --m /models/cori/model
      --length-scale 1.1
      --noise-scale 0.8
      --noise-w-scale 0.7
      --host 0.0.0.0
    volumes:
      - ./piper/models:/models
